dist: xenial
language: python
python: 3.7

services:
  - redis-server

install:
  - pip install -r requirements.txt

script:
  - yamllint websites.yml
  - python tests.py

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
