language: generic

services:
  - docker

before_script:
  - pip install -r requirements.txt
  -

script:
  - python tests.py

deploy:
  provider: heroku
  api_key:
    secure: "YOUR ENCRYPTED API KEY"