version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=127.0.0.1
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  # api:
  #   container_name: changedetection-api
  #   build:
  #     context: ./
  #   image: changedetection-api
  #   depends_on:
  #     - db
  #   ports:
  #     - 3000:3000
  #   environment:
  #     NODE_ENV: production
  #     DB_HOST: db
  #     DB_PORT: 5432
  #     DB_USER: postgres
  #     DB_PASSWORD: postgres
  #     DB_NAME: postgres
  #   links:
  #     - db
  #   volumes:
  #     - './:/src'
volumes:
  db:
    driver: local
networks:
  timescaledb:
    driver: bridge
