# fly.toml app configuration file generated for changedetection-a32cf on 2023-10-06T07:29:47+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "changedetection-a32cf"
primary_region = "syd"

[build]

[deploy]
  release_command = "alembic upgrade head"

[processes]
  app = "uvicorn app.main:app --host 0.0.0.0 --port 3000"
  worker = "python main.py"

[mounts]
  source="changedetection_data"
  destination="/data"
  processes= ["worker"]

[[services]]
  protocol = ""
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["worker"]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
