# fly.toml app configuration file generated for changedetection-db on 2023-10-29T15:24:38+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "changedetection-db"
primary_region = "syd"

[checks.pg]
interval = "15s"
path = "/flycheck/pg"
port = 5_500
timeout = "10s"
type = "http"

[checks.role]
interval = "15s"
path = "/flycheck/role"
port = 5_500
timeout = "10s"
type = "http"

[checks.vm]
interval = "15s"
path = "/flycheck/vm"
port = 5_500
timeout = "10s"
type = "http"

[env]
FLY_SCALE_TO_ZERO = "1h"
PRIMARY_REGION = "syd"

[[metrics]]
path = "/metrics"
port = 9_187

[[mounts]]
destination = "/data"
source = "pg_data"

[[services]]
auto_start_machines = true
auto_stop_machines = true
internal_port = 5_432
protocol = "tcp"

  [services.concurrency]
  hard_limit = 1_000
  soft_limit = 1_000
  type = "connections"

  [[services.ports]]
  handlers = [ "pg_tls" ]
  port = 5_432

[[services]]
auto_start_machines = true
auto_stop_machines = true
internal_port = 5_433
protocol = "tcp"

  [services.concurrency]
  hard_limit = 1_000
  soft_limit = 1_000
  type = "connections"

  [[services.ports]]
  handlers = [ "pg_tls" ]
  port = 5_433